apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.fullname" . }}
  labels:
{{ include "authelia.labels" . | indent 4 }}
data:
  configuration.yaml: |
    host: 0.0.0.0
    port: 9091
    server:
      read_buffer_size: 4096
      write_buffer_size: 4096
{{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
{{- end }}
